name: Platform Check

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  check-platform:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check System Info
        run: |
          uname -m
          docker info | grep "OS/Arch"
          docker buildx ls
