name: Release Pipeline for publishing

on:
  release:
    types: [published]

env:
  APP_NAME: Place.API
  SOLUTION: Place.sln
  API_PROJECT: src/Place.API/Place.API.csproj

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props', '**/*.targets') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Build and Test
      - name: Restore dependencies
        run: make restore SOLUTION=${{ env.SOLUTION }}

      - name: Build solution
        run: make build SOLUTION=${{ env.SOLUTION }}

      - name: Run unit tests
        run: make test-unit SOLUTION=${{ env.SOLUTION }}

      - name: Run integration tests
        run: make test-integration SOLUTION=${{ env.SOLUTION }}

      # Publish binaries
      - name: Publish x64
        run: make publish RUNTIME=linux-musl-x64 API_PROJECT=${{ env.API_PROJECT }} APP_NAME=${{ env.APP_NAME }}
        env:
          PUBLISH_OUTPUT: ./publish/x64

      - name: Publish arm64
        run: make publish RUNTIME=linux-musl-arm64 API_PROJECT=${{ env.API_PROJECT }} APP_NAME=${{ env.APP_NAME }}
        env:
          PUBLISH_OUTPUT: ./publish/arm64

      # Create release assets
      - name: Create ZIP files
        run: |
          cd publish
          zip -r ../${{ env.APP_NAME }}-linux-x64.zip x64/*
          zip -r ../${{ env.APP_NAME }}-linux-arm64.zip arm64/*

      # Upload to release
      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} \
            ${{ env.APP_NAME }}-linux-x64.zip \
            ${{ env.APP_NAME }}-linux-arm64.zip \
            --clobber

      # Docker Setup
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker images
      - name: Build x64 Docker image
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          make docker RUNTIME=linux-musl-x64 APP_NAME=${{ env.APP_NAME }} \
            DOCKER_TAG=ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}
          docker tag ${{ env.APP_NAME }}-x64 ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:${VERSION}-x64
          docker push ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:${VERSION}-x64
          docker push ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:latest-x64

      - name: Build arm64 Docker image
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          make docker RUNTIME=linux-musl-arm64 APP_NAME=${{ env.APP_NAME }} \
            DOCKER_TAG=ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}
          docker tag ${{ env.APP_NAME }}-arm64 ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:${VERSION}-arm64
          docker push ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:${VERSION}-arm64
          docker push ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:latest-arm64

      # Create and push multi-arch manifest
      - name: Create and push multi-arch manifest
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          
          # Enable experimental features for manifest
          export DOCKER_CLI_EXPERIMENTAL=enabled
          
          # Create and push version manifest
          docker manifest create ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:${VERSION} \
            ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:${VERSION}-x64 \
            ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:${VERSION}-arm64
          
          docker manifest annotate ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:${VERSION} \
            ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:${VERSION}-x64 --arch amd64
          
          docker manifest annotate ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:${VERSION} \
            ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:${VERSION}-arm64 --arch arm64
          
          docker manifest push ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:${VERSION}
          
          # Create and push latest manifest
          docker manifest create ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:latest \
            ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:latest-x64 \
            ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:latest-arm64
          
          docker manifest annotate ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:latest \
            ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:latest-x64 --arch amd64
          
          docker manifest annotate ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:latest \
            ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:latest-arm64 --arch arm64
          
          docker manifest push ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:latest

      # Optional: Cleanup
      - name: Cleanup
        if: always()
        run: make clean SOLUTION=${{ env.SOLUTION }}