name: Release

on:
  push:
    branches: [ "main" ]  # Changé de pull_request à push
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write


jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.GITHUB_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: simple
          target-branch: main
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
